image: node:14

stages:
    - Validate node
    - Build and configure
    - Run tests without report
    - Run tests with Allure

Pre-reqs:
    stage: Validate node
    script:
        - node -v
        - npm -v

Configure:
    stage: Build and configure
    dependencies:
        - Pre-reqs
    script:
        - npm install
    artifacts:
        paths:
            - node_modules/
        expire_in: 3 hrs
    cache:
        untracked: true
        key: "$CI_BUILD_REF_NAME"
        paths:
            - node_modules/
            - .npm/

Test-API-NoReport:  
    image: cypress/browsers:node14.17.0-chrome91-ff89
    stage: Run tests without report
    dependencies:
        - Configure
    script:
        - npm ci
        - npm run start:ci &
        - npm run test:api
    artifacts:
        when: always
        paths:
          - cypress/videos/**/*.mp4
          - cypress/screenshots/**/*.png
        expire_in: 2 hrs
    allow_failure: false

Test-UI-Chrome-NoReport:  
    image: cypress/browsers:node14.17.0-chrome91-ff89
    stage: Run tests without report
    dependencies:
        - Configure
    script:
        - npm ci
        - npm run start:ci &
        - npm run test:ui:chrome
    artifacts:
        when: always
        paths:
          - cypress/videos/**/*.mp4
          - cypress/screenshots/**/*.png
        expire_in: 2 hrs
    allow_failure: false

Test-UI-Firefox-NoReport:  
    image: cypress/browsers:node14.17.0-chrome91-ff89
    stage: Run tests without report
    dependencies:
        - Configure
    script:
        - npm ci
        - npm run start:ci &
        - npm run test:ui:firefox
    artifacts:
        when: always
        paths:
          - cypress/videos/**/*.mp4
          - cypress/screenshots/**/*.png
        expire_in: 2 hrs
    allow_failure: false

Test-API-Allure:  
    image: cypress/browsers:node14.17.0-chrome91-ff89
    stage: Run tests with Allure
    dependencies:
        - Configure
    script:
        - npm ci
        - npm run start:ci &
        - npm run test:api:allure
    artifacts:
        when: always
        paths:
          - cypress/videos/**/*.mp4
          - cypress/screenshots/**/*.png
          - allure-report
          - allure-results
        expire_in: 2 hrs
    allow_failure: true

Test-UI-Chrome-Allure:  
    image: cypress/browsers:node14.17.0-chrome91-ff89
    stage: Run tests with Allure
    dependencies:
        - Configure
    script:
        - npm ci
        - npm run start:ci &
        - npm run test:ui:chrome:allure
    artifacts:
        when: always
        paths:
          - cypress/videos/**/*.mp4
          - cypress/screenshots/**/*.png
          - allure-report
          - allure-results
        expire_in: 2 hrs
    allow_failure: true

Test-UI-Firefox-Allure:  
    image: cypress/browsers:node14.17.0-chrome91-ff89
    stage: Run tests with Allure
    dependencies:
        - Configure
    script:
        - npm ci
        - npm run start:ci &
        - npm run test:ui:firefox:allure
    artifacts:
        when: always
        paths:
          - cypress/videos/**/*.mp4
          - cypress/screenshots/**/*.png
          - allure-report
          - allure-results
        expire_in: 2 hrs
    allow_failure: true
