image: node:14

stages:
    - Validate node
    - Build and configure
    - Run API tests
    - Run UI on Chrome
    - Run UI on Firefox

Pre-reqs:
    stage: Validate node
    script:
        - npx ascii-themes generate 'CHECK FOR CYPRESS PRE-REQS' --font 'Greek'
        - node -v
        - npm -v

Configure:
    stage: Build and configure
    dependencies:
        - Pre-check
    script:
        - npx ascii-themes generate 'INSTALL DEPENDENCIES' --font 'Greek'
        - npm install
    artifacts:
        paths:
            - node_modules/
        expire_in: 3 hrs
    cache:
        untracked: true
        key: "$CI_BUILD_REF_NAME"
        paths:
            - node_modules/
            - .npm/

Test API:  
    image: cypress/browsers:node14.17.0-chrome91-ff89
    stage: Run API tests
    dependencies:
        - Configure
    script:
        - npx ascii-themes generate 'CYPRESS API TESTING' --font 'Greek'
        - npm run test:api
    artifacts:
        when: always
        paths:
          - cypress/videos/**/*.mp4
          - cypress/screenshots/**/*.png
        expire_in: 2 hrs
    allow_failure: true

Test UI:  
    image: cypress/browsers:node14.17.0-chrome91-ff89
    stage: Run UI on Chrome
    dependencies:
        - Configure
    script:
        - npx ascii-themes generate 'CYPRESS TESTING ON CHROME' --font 'Greek'
        - npm run test:ui:chrome
    artifacts:
        when: always
        paths:
          - cypress/videos/**/*.mp4
          - cypress/screenshots/**/*.png
        expire_in: 2 hrs
    allow_failure: true

Test UI:  
    image: cypress/browsers:node14.17.0-chrome91-ff89
    stage: Run UI on Firefox
    dependencies:
        - Configure
    script:
        - npx ascii-themes generate 'CYPRESS TESTING ON CHROME' --font 'Greek'
        - npm run test:ui:firefox
    artifacts:
        when: always
        paths:
          - cypress/videos/**/*.mp4
          - cypress/screenshots/**/*.png
        expire_in: 2 hrs
    allow_failure: true
